/**
 * The derived topology, imported at build time.
 *
 * `contracts/topology.json` is generated by `scripts/scan_topology.py` and held to the
 * tree by `scripts/check_topology_drift.py`, so importing it here is importing the
 * derivation chain's output, not a hand-kept list (022 FR-001). The import is the same
 * arrangement `contracts/schemas.ts` uses for the masters: one definition, above this
 * package, read rather than copied.
 *
 * Nothing in the document is a claim about a running system — no component is said to
 * exist, to be alive, or ever to have sent anything — and nothing built from it may
 * light a cell. Structure comes from here; illumination comes from received traffic;
 * the two never mix (Constitution VII).
 */
import topologyDocument from "../../../contracts/topology.json";
import type { DrognaBrokerTopology } from "../generated/messages/topology";

export const TOPOLOGY: DrognaBrokerTopology = topologyDocument as DrognaBrokerTopology;
