#!/usr/bin/env python3
"""Gate: the committed topology artefact still matches a fresh scan of the tree.

``contracts/topology.json`` is generated by ``scripts/scan_topology.py`` from the access
control list, the destination configurations and the components' own source. Generated
content that is committed is only trustworthy if something proves it current — the same
argument that gives the generated type trees ``scripts/check_types_drift.sh`` — and the
consequence of it going stale here is worse than a stale type, because feature 018's
matrix draws its structure from this document and a drawing that can rot silently is a
second ``tasks.md``.

The gate is the scan's own check mode. It writes nothing whether it passes or fails,
reaches no network, starts no service and needs no broker: it reads the documents in the
repository and nothing else, which is what lets it run in the same job as every other gate.

It fails on all of: a topic added to a component without the artefact being regenerated, a
topic removed, an access control rule changed, a component's broker role changed, and the
artefact edited by hand. It also fails when a topic is written somewhere the scan cannot
see it — straight into a call rather than bound to a module-level constant — because an
artefact that cannot see a topic is worse than none: it reads as a complete list.

Registered by one appended line in ``scripts/gates.registry``. ``scripts/gates.sh`` names
no gate and is not edited.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from scan_topology import main

if __name__ == "__main__":
    raise SystemExit(main(["--check"]))
