#!/usr/bin/env python3
"""The generator chain: neutral masters in, committed types in two languages out.

Constitution III in one program. Every shape that crosses a language boundary is written
once, as JSON Schema under ``contracts/schemas/`` or as OpenAPI under
``contracts/openapi/``, and this script turns those masters into Pydantic v2 models under
``libs/harness_types/`` and TypeScript types under ``client/src/generated/``. Both trees
are committed so a checkout builds without a generator, and both are compared byte for
byte in CI so a committed tree cannot quietly disagree with its source.

Run it two ways::

    scripts/generate_types.sh          # rewrite the generated trees
    scripts/check_types_drift.sh       # regenerate to scratch, diff, fail on difference

The steps, in order:

1. **Discover.** Every ``contracts/schemas/*.schema.json`` is a master. A name beginning
   ``config.`` is a configuration schema and lands under ``config/``; everything else is
   a payload and lands under ``messages/``. That rule is mechanical on purpose: adding a
   shape means adding one file and running one script, and never editing a list.
2. **Bundle.** The masters are copied to a scratch directory with their external
   references rewritten to bundle-relative form, and every reference — internal or not —
   is resolved there and then. A reference that does not resolve inside the repository is
   a failure, never a network fetch (FR-016). The bundle is a build artefact; the
   documents under ``contracts/`` stay authoritative.
3. **Generate.** datamodel-code-generator writes the Python; the emitter in
   ``schema_to_typescript`` writes the TypeScript. Both are pinned in
   ``contracts/openapi/generators.toml`` and both versions are checked before a byte is
   written.
4. **Normalise and banner.** The generator's own header is replaced by one naming the
   master and this script, line endings are made uniform, and the output is checked for
   the two things that would make the drift check fail for no reason anyone caused: an
   embedded timestamp, and a path from the machine that ran it.
5. **Copy.** The schema documents that travel inside component packages are copied from
   their masters, which is what makes those copies an output of this chain rather than a
   second hand-maintained tree. The tests asserting each copy matches its master are
   unchanged, and now cannot fail without this check failing first.

Nothing is written outside the generated trees, and in check mode nothing is written at
all.
"""

from __future__ import annotations

import argparse
import difflib
import json
import os
import subprocess
import sys
import tempfile
import tomllib
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent))

from schema_to_typescript import EMITTER_VERSION, GenerationError, Target, emit_module, type_name

REPO_ROOT = Path(__file__).resolve().parent.parent

SCHEMA_DIRECTORY = Path("contracts") / "schemas"
MANIFEST_FILE = Path("contracts") / "openapi" / "generators.toml"
PYTHON_PACKAGE = Path("libs") / "harness_types" / "src" / "harness_types"
TYPESCRIPT_PACKAGE = Path("client") / "src" / "generated"

SCHEMA_SUFFIX = ".schema.json"
IDENTIFIER_PREFIX = "https://schemas.harness.invalid/"

GENERATE_COMMAND = "scripts/generate_types.sh"
CHECK_COMMAND = "scripts/check_types_drift.sh"

EXIT_CLEAN = 0
EXIT_DRIFT = 1
EXIT_FAILURE = 2

# The header datamodel-code-generator writes for itself. Replaced rather than kept: it
# names the bundled intermediate, which is a scratch file nobody can open, where the
# banner has to name the master a reader can.
CODEGEN_HEADER = "# generated by datamodel-codegen:"


class ChainError(Exception):
    """Something the chain will not proceed past, stated in one readable line."""


# ---------------------------------------------------------------------------------
# Masters
# ---------------------------------------------------------------------------------


@dataclass(frozen=True)
class Master:
    """One authoritative schema document, and where its generated output goes."""

    path: Path  # repository-relative
    stem: str  # `run_manifest` for run-manifest.schema.json
    category: str  # `config` or `messages`

    @property
    def bundle_path(self) -> Path:
        return Path(self.category) / f"{self.stem}.json"

    @property
    def python_path(self) -> Path:
        return PYTHON_PACKAGE / self.category / f"{self.stem}.py"

    @property
    def typescript_path(self) -> Path:
        return TYPESCRIPT_PACKAGE / self.category / f"{self.stem}.ts"


def load_manifest(root: Path) -> Mapping[str, Any]:
    path = root / MANIFEST_FILE
    if not path.is_file():
        raise ChainError(f"the generator manifest is missing: {MANIFEST_FILE}")
    with path.open("rb") as handle:
        return tomllib.load(handle)


def discover_masters(root: Path, manifest: Mapping[str, Any]) -> list[Master]:
    """Every master under ``contracts/schemas/``, classified and checked for collisions."""
    settings = manifest.get("bundle", {})
    prefix = settings.get("config_prefix", "config.")
    config_directory = settings.get("config_directory", "config")
    message_directory = settings.get("message_directory", "messages")

    masters: list[Master] = []
    directory = root / SCHEMA_DIRECTORY
    if not directory.is_dir():
        raise ChainError(f"no schema directory at {SCHEMA_DIRECTORY}")
    for path in sorted(directory.glob("*" + SCHEMA_SUFFIX)):
        name = path.name[: -len(SCHEMA_SUFFIX)]
        if name.startswith(prefix):
            category, stem = config_directory, name[len(prefix) :]
        else:
            category, stem = message_directory, name
        stem = stem.replace("-", "_").replace(".", "_")
        masters.append(
            Master(path=path.relative_to(root), stem=stem, category=category),
        )

    _refuse_collisions(root, masters)
    return masters


def _refuse_collisions(root: Path, masters: Sequence[Master]) -> None:
    """Two masters may not claim one module or one type name.

    Either would mean one shape silently winning over another, which is the failure the
    whole feature exists to make impossible. Both source files are named, because the
    person reading the error has to choose which one to rename.
    """
    by_module: dict[Path, Master] = {}
    for master in masters:
        clash = by_module.get(master.bundle_path)
        if clash is not None:
            raise ChainError(
                f"{master.path} and {clash.path} both generate {master.bundle_path}; "
                "rename one of the masters"
            )
        by_module[master.bundle_path] = master

    by_type: dict[str, Master] = {}
    for master in masters:
        document = json.loads((root / master.path).read_text(encoding="utf-8"))
        title = document.get("title")
        if not title:
            raise ChainError(f"{master.path} has no title; the generated type has no name")
        name = type_name(title)
        clash = by_type.get(name)
        if clash is not None:
            raise ChainError(
                f"{master.path} and {clash.path} both generate the type {name!r}; "
                "one shape, one name — change a title"
            )
        by_type[name] = master


# ---------------------------------------------------------------------------------
# Bundling
# ---------------------------------------------------------------------------------


def _pointer(document: Mapping[str, Any], fragment: str, where: str) -> None:
    """Assert that a JSON pointer resolves, so a typo fails here and not later."""
    node: Any = document
    for token in [part for part in fragment.split("/") if part]:
        token = token.replace("~1", "/").replace("~0", "~")
        if not isinstance(node, Mapping) or token not in node:
            raise ChainError(f"{where}: reference to {fragment!r} does not resolve")
        node = node[token]


def _resolve_reference(
    reference: str,
    master: Master,
    documents: Mapping[str, tuple[Master, Mapping[str, Any]]],
    where: str,
) -> tuple[str, str]:
    """Return (bundle-relative document, fragment) for one ``$ref``.

    Every reference must land on a document in this repository. Nothing here consults the
    network, and the generator is installed without the extra that would let it try.
    """
    document, _, fragment = reference.partition("#")
    fragment = "#" + fragment if fragment else ""
    if not document:
        return "", fragment

    target = document
    if target.startswith(IDENTIFIER_PREFIX):
        target = target[len(IDENTIFIER_PREFIX) :]
    if target.startswith("http://") or target.startswith("https://"):
        raise ChainError(
            f"{where}: reference to {reference!r} names a document outside the repository; "
            "generation never reaches the network"
        )
    target = target.rsplit("/", 1)[-1]
    entry = documents.get(target)
    if entry is None:
        raise ChainError(
            f"{where}: reference to {reference!r} does not name a master in "
            f"{SCHEMA_DIRECTORY}"
        )
    other, other_document = entry
    if fragment:
        _pointer(other_document, fragment[1:], where)
    relative = os.path.relpath(other.bundle_path, master.bundle_path.parent)
    return Path(relative).as_posix(), fragment


def _rewrite(
    node: Any,
    master: Master,
    documents: Mapping[str, tuple[Master, Mapping[str, Any]]],
    document: Mapping[str, Any],
    where: str,
) -> Any:
    if isinstance(node, Mapping):
        rewritten: dict[str, Any] = {}
        for key, value in node.items():
            if key == "$ref" and isinstance(value, str):
                if value.startswith("#"):
                    _pointer(document, value[1:], where)
                    rewritten[key] = value
                    continue
                target, fragment = _resolve_reference(value, master, documents, where)
                rewritten[key] = f"{target}{fragment}"
                continue
            rewritten[key] = _rewrite(value, master, documents, document, where)
        return rewritten
    if isinstance(node, list):
        return [_rewrite(item, master, documents, document, where) for item in node]
    return node


def bundle(root: Path, masters: Sequence[Master], destination: Path) -> dict[Path, Any]:
    """Write the bundle and return each master's rewritten document."""
    documents: dict[str, tuple[Master, Mapping[str, Any]]] = {}
    for master in masters:
        documents[master.path.name] = (
            master,
            json.loads((root / master.path).read_text(encoding="utf-8")),
        )

    bundled: dict[Path, Any] = {}
    for master in masters:
        _, document = documents[master.path.name]
        rewritten = _rewrite(document, master, documents, document, str(master.path))
        target = destination / master.bundle_path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(json.dumps(rewritten, indent=2, ensure_ascii=False) + "\n", "utf-8")
        bundled[master.bundle_path] = rewritten
    return bundled


# ---------------------------------------------------------------------------------
# Banners and normalisation
# ---------------------------------------------------------------------------------


def banner(source: str, comment: str) -> str:
    """The DO NOT EDIT banner, naming what wrote the file and from what."""
    lines = (
        "DO NOT EDIT.",
        f"Generated from {source} by {GENERATE_COMMAND}.",
        f"Edit the master and run that script; {CHECK_COMMAND} fails the build on a hand edit.",
    )
    return "\n".join(f"{comment} {line}" for line in lines)


def normalise(text: str, *, source: str, comment: str, scratch: Path) -> str:
    """Strip the generator's own header, apply the banner, and refuse unstable output."""
    lines = text.replace("\r\n", "\n").replace("\r", "\n").split("\n")
    while lines and (lines[0].startswith(CODEGEN_HEADER) or lines[0].startswith("#   filename:")):
        lines.pop(0)
    while lines and not lines[0].strip():
        lines.pop(0)
    body = "\n".join(lines).rstrip("\n")
    rendered = f"{banner(source, comment)}\n\n{body}\n" if body else f"{banner(source, comment)}\n"

    scratch_text = scratch.as_posix()
    if scratch_text in rendered:
        raise ChainError(
            f"generated output for {source} carries the scratch path {scratch_text}; "
            "the generator leaked the machine it ran on and the tree would differ per machine"
        )
    return rendered


# ---------------------------------------------------------------------------------
# The two generators
# ---------------------------------------------------------------------------------


def _tools(manifest: Mapping[str, Any]) -> dict[str, Mapping[str, Any]]:
    return {entry["name"]: entry for entry in manifest.get("tool", [])}


def _installed_version(module: str) -> str:
    from importlib.metadata import PackageNotFoundError, version

    try:
        return version(module)
    except PackageNotFoundError as error:  # pragma: no cover - an unsynced environment
        raise ChainError(
            f"{module} is not installed; run `uv sync` before generating types"
        ) from error


def check_versions(manifest: Mapping[str, Any]) -> None:
    """Refuse to generate with a tool other than the one the committed tree was written by.

    Not pedantry: the drift check compares bytes, so a generator at a different version
    produces a diff that nobody's change caused and that everybody learns to ignore.
    """
    tools = _tools(manifest)
    for package in ("datamodel-code-generator", "black", "isort"):
        pinned = tools.get(package, {}).get("version")
        installed = _installed_version(package)
        if pinned is not None and pinned != installed:
            raise ChainError(
                f"{package} {installed} is installed but {MANIFEST_FILE} pins {pinned}; "
                "generate with the pinned version, or change the pin and regenerate "
                "the whole tree in one commit"
            )
    emitter = tools.get("drogna-schema-to-typescript", {}).get("version")
    if emitter is not None and emitter != EMITTER_VERSION:
        raise ChainError(
            f"the TypeScript emitter is version {EMITTER_VERSION} but {MANIFEST_FILE} pins "
            f"{emitter}; bump the pin in the same commit as the emitter change"
        )


def generate_python(
    manifest: Mapping[str, Any],
    masters: Sequence[Master],
    bundle_directory: Path,
    scratch: Path,
) -> dict[Path, str]:
    """Run datamodel-code-generator over the bundle and return the banner-marked modules."""
    options = [str(option) for option in manifest["python"]["options"]]
    output = scratch / "python"
    command = [
        sys.executable,
        "-m",
        "datamodel_code_generator",
        "--input",
        str(bundle_directory),
        "--output",
        str(output),
        *options,
    ]
    result = subprocess.run(  # noqa: S603 - fixed command, no shell
        command,
        capture_output=True,
        text=True,
        check=False,
        cwd=str(scratch),
    )
    if result.returncode != 0:
        raise ChainError(
            "datamodel-code-generator failed:\n" + (result.stderr or result.stdout).strip()
        )

    by_bundle = {master.bundle_path: master for master in masters}
    generated: dict[Path, str] = {}
    for path in sorted(output.rglob("*.py")):
        relative = path.relative_to(output)
        if relative.name == "__init__.py":
            source = str(SCHEMA_DIRECTORY)
            destination = PYTHON_PACKAGE / relative
        else:
            master = by_bundle.get(relative.with_suffix(".json"))
            if master is None:
                raise ChainError(f"the Python generator wrote an unexpected module: {relative}")
            source = str(master.path)
            destination = master.python_path
        generated[destination] = normalise(
            path.read_text(encoding="utf-8"),
            source=source,
            comment="#",
            scratch=scratch,
        )
    return generated


def generate_typescript(
    masters: Sequence[Master],
    bundled: Mapping[Path, Any],
    scratch: Path,
) -> dict[Path, str]:
    """Emit one TypeScript module per master, importing shared shapes rather than restating."""
    by_bundle = {master.bundle_path: master for master in masters}
    generated: dict[Path, str] = {}
    for master in masters:
        document = bundled[master.bundle_path]

        def resolve(reference: str, master: Master = master) -> Target:
            document_part, _, fragment = reference.partition("#")
            name_source = fragment.rsplit("/", 1)[-1] if fragment else None
            if not document_part:
                if not name_source:
                    raise GenerationError(f"{master.path}: a bare '#' reference")
                return Target(type_name(name_source), None)
            other = by_bundle[
                Path(os.path.normpath(master.bundle_path.parent / document_part)).relative_to(".")
                if False
                else Path(os.path.normpath(str(master.bundle_path.parent / document_part)))
            ]
            if not name_source:
                other_document = bundled[other.bundle_path]
                name_source = other_document["title"]
            relative = os.path.relpath(
                other.typescript_path.with_suffix(""),
                master.typescript_path.parent,
            )
            module = Path(relative).as_posix()
            if not module.startswith("."):
                module = f"./{module}"
            return Target(type_name(name_source), module)

        text = emit_module(
            document,
            source=str(master.path),
            resolve=resolve,
            banner=banner(str(master.path), "//"),
        )
        generated[master.typescript_path] = normalise(
            text,
            source=str(master.path),
            comment="//",
            scratch=scratch,
        )
    return generated


# ---------------------------------------------------------------------------------
# The tree
# ---------------------------------------------------------------------------------


def generated_tree(root: Path, scratch: Path) -> dict[Path, str]:
    """Every generated file, as text, keyed by repository-relative path."""
    manifest = load_manifest(root)
    check_versions(manifest)
    masters = discover_masters(root, manifest)

    bundle_directory = scratch / "bundle"
    bundled = bundle(root, masters, bundle_directory)

    tree: dict[Path, str] = {}
    tree.update(generate_python(manifest, masters, bundle_directory, scratch))
    tree.update(generate_typescript(masters, bundled, scratch))

    for entry in manifest.get("copy", []):
        source = root / entry["source"]
        if not source.is_file():
            raise ChainError(f"the manifest copies {entry['source']}, which does not exist")
        tree[Path(entry["target"])] = source.read_text(encoding="utf-8")

    return dict(sorted(tree.items()))


def committed_tree(root: Path, manifest: Mapping[str, Any]) -> dict[Path, str]:
    """Every file the chain owns that is currently on disk.

    Read separately from the generated tree so that a file left behind by a deleted
    master is a difference rather than something nobody notices.
    """
    found: dict[Path, str] = {}
    for directory, suffix in ((PYTHON_PACKAGE, ".py"), (TYPESCRIPT_PACKAGE, ".ts")):
        base = root / directory
        if not base.is_dir():
            continue
        for path in sorted(base.rglob("*" + suffix)):
            found[path.relative_to(root)] = path.read_text(encoding="utf-8")
    for entry in manifest.get("copy", []):
        path = root / entry["target"]
        if path.is_file():
            found[Path(entry["target"])] = path.read_text(encoding="utf-8")
    return dict(sorted(found.items()))


def write_tree(root: Path, tree: Mapping[Path, str], manifest: Mapping[str, Any]) -> list[str]:
    """Write the generated tree, removing anything the masters no longer account for."""
    changed: list[str] = []
    for relative, text in tree.items():
        path = root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        if not path.is_file() or path.read_text(encoding="utf-8") != text:
            path.write_text(text, encoding="utf-8")
            changed.append(str(relative))
    for relative in committed_tree(root, manifest):
        if relative not in tree:
            (root / relative).unlink()
            changed.append(f"{relative} (removed)")
    return changed


def diff_tree(root: Path, tree: Mapping[Path, str], manifest: Mapping[str, Any]) -> list[str]:
    """Every difference between the committed tree and a fresh generation, as a diff."""
    committed = committed_tree(root, manifest)
    differences: list[str] = []
    for relative in sorted(set(tree) | set(committed)):
        expected = tree.get(relative)
        actual = committed.get(relative)
        if expected == actual:
            continue
        if expected is None:
            differences.append(
                f"{relative}: present in the repository but no master generates it. "
                "Delete it, or add the master it should have come from."
            )
            continue
        if actual is None:
            differences.append(f"{relative}: missing. Run {GENERATE_COMMAND}.")
            continue
        lines = difflib.unified_diff(
            actual.splitlines(keepends=True),
            expected.splitlines(keepends=True),
            fromfile=f"{relative} (committed)",
            tofile=f"{relative} (regenerated)",
        )
        differences.append("".join(lines).rstrip("\n"))
    return differences


# ---------------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------------


def run(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="drogna generated-types chain")
    parser.add_argument(
        "--check",
        action="store_true",
        help="regenerate into a scratch directory and diff; write nothing",
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=REPO_ROOT,
        help="repository root to read and write (the real one by default)",
    )
    parser.add_argument(
        "--into",
        type=Path,
        default=None,
        help="write the generated tree under this directory instead of the repository",
    )
    arguments = parser.parse_args(argv)
    root = arguments.root.resolve()

    try:
        with tempfile.TemporaryDirectory(prefix="drogna-types-") as scratch_name:
            scratch = Path(scratch_name)
            tree = generated_tree(root, scratch)
            manifest = load_manifest(root)

            if arguments.check:
                differences = diff_tree(root, tree, manifest)
                if differences:
                    print("\n\n".join(differences))
                    print(
                        f"\ngenerated types: {len(differences)} file(s) differ from their "
                        f"masters. Run {GENERATE_COMMAND} and commit the result."
                    )
                    return EXIT_DRIFT
                print(f"generated types: {len(tree)} file(s) match their masters.")
                return EXIT_CLEAN

            destination = (arguments.into or root).resolve()
            changed = write_tree(destination, tree, manifest)
            for entry in changed:
                print(f"wrote {entry}")
            print(f"generated types: {len(tree)} file(s) from {SCHEMA_DIRECTORY}.")
            return EXIT_CLEAN
    except (ChainError, GenerationError) as error:
        print(f"generated types: {error}", file=sys.stderr)
        return EXIT_FAILURE


if __name__ == "__main__":
    raise SystemExit(run())
