"""The committed topology artefact still describes this repository.

`contracts/topology.json` is generated by `scripts/scan_topology.py` and guarded by
`scripts/check_topology_drift.py`, which is registered in `scripts/gates.registry`. These
tests are the same claim from inside `pytest`, and they are here rather than left to the
gate for one reason: the gates are a separate command, and a contributor who runs the tests
and not the gates would otherwise commit a stale artefact and find out in CI.

They also assert two things the gate cannot. That the document validates against its own
master through the same validator every component uses — a generated document that does
not satisfy the schema it is generated for is a defect in the generator, not in the tree.
And that every source location it records still holds the topic it claims, which is the
property that decays first: a file gets an import added at the top and every line number
below it moves.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

from harness_core.config import validate_document
from harness_types.messages.topology import DrognaBrokerTopology

REPO_ROOT = Path(__file__).resolve().parents[2]
ARTEFACT = REPO_ROOT / "contracts" / "topology.json"
MASTER = REPO_ROOT / "contracts" / "schemas" / "topology.schema.json"

sys.path.insert(0, str(REPO_ROOT / "scripts"))

from scan_topology import build, render  # noqa: E402


def artefact() -> dict:
    return json.loads(ARTEFACT.read_text(encoding="utf-8"))


def test_the_artefact_matches_a_fresh_scan_of_the_tree() -> None:
    """The tree is the authority and the artefact is a claim about it."""
    document, findings = build(REPO_ROOT)

    assert findings == [], "\n".join(findings)
    assert ARTEFACT.read_text(encoding="utf-8") == render(document), (
        "contracts/topology.json disagrees with the tree; run "
        "`uv run python scripts/scan_topology.py` and commit what it writes"
    )


def test_the_artefact_validates_against_its_master() -> None:
    schema = json.loads(MASTER.read_text(encoding="utf-8"))

    validate_document(artefact(), schema, source="topology")


def test_the_artefact_parses_through_its_generated_model() -> None:
    """Both language forms come from the master; this is the Python one, exercised."""
    model = DrognaBrokerTopology.model_validate(artefact())

    assert model.generator == "scripts/scan_topology.py"
    assert model.topics, "an artefact with no topics is not a clean scan, it is an empty one"


def test_every_recorded_source_location_still_holds_its_topic() -> None:
    """The claim that decays first: an added import moves every line beneath it."""
    for entry in artefact()["topics"]:
        for site in entry["named_by"]:
            line = (
                (REPO_ROOT / site["path"])
                .read_text(encoding="utf-8")
                .splitlines()[site["line"] - 1]
            )
            assert site["constant"] in line, f"{site['path']}:{site['line']} — {line.strip()}"
            found = re.search(r"""(['"])((?:obs|ctl)/[^'"]*)\1""", line)
            assert found is not None, f"{site['path']}:{site['line']} names no topic"
            expected = entry["topic"].removesuffix("#")
            assert found.group(2).startswith(expected) or found.group(2) == entry["topic"], (
                f"{site['path']}:{site['line']} names {found.group(2)!r}, "
                f"recorded under {entry['topic']!r}"
            )


def test_every_component_authenticates_as_a_role_the_broker_grants() -> None:
    """Mosquitto denies by default: a role with no block can do nothing once connected."""
    granted = {role["role"] for role in artefact()["roles"]}

    for component in artefact()["components"]:
        assert component["role"] in granted, (
            f"{component['id']} authenticates as {component['role']}, "
            "which the access control list grants nothing"
        )


def test_the_sensors_are_confined_to_the_observation_branch() -> None:
    """ADR-0012 and FR-14, read out of the derived document rather than out of prose.

    The one control topic a sensor may write is its heartbeat, and the one it may read is
    the clock. That pair is argued for at length in `deploy/broker/acl`; this is the
    assertion that the argument still describes the file.
    """
    document = artefact()
    writable = {entry["topic"] for entry in document["topics"] if "sensors" in entry["publishers"]}
    readable = {entry["topic"] for entry in document["topics"] if "sensors" in entry["subscribers"]}

    # The claim is confinement, so it is asserted as confinement: the writable set is the
    # observation branch — the filter and the concrete topics feature 022's expansion
    # spells under it — plus the one argued control topic, and nothing else. An
    # enumeration of the concrete topics here would be a second copy of the sensor
    # configuration, going stale the day a datastream is added.
    assert "obs/#" in writable
    assert "ctl/heartbeat" in writable
    assert all(topic.startswith("obs/") or topic == "ctl/heartbeat" for topic in writable)
    assert readable == {"ctl/clock"}


def test_the_query_layer_subscribes_to_nothing() -> None:
    """C-09 serves reads over HTTP; freshness reaches it through the query path."""
    subscribed = [
        entry["topic"] for entry in artefact()["topics"] if "query" in entry["subscribers"]
    ]

    assert subscribed == []


def test_the_browser_can_publish_nowhere() -> None:
    """ADR-0008, extended by ADR-0027: the browser's identity has no write rule.

    The client now authenticates as `drogna_observer` (feature 022), which reads both
    namespaces — and the property that made its credential publishable is the one this
    test holds: gaining any write rule would be a voice.
    """
    published = [
        entry["topic"] for entry in artefact()["topics"] if "client" in entry["publishers"]
    ]

    assert published == []


def test_every_topic_names_the_master_that_governs_it() -> None:
    """A topic with no governing shape is a payload nothing validates."""
    for entry in artefact()["topics"]:
        assert entry["schema"] is not None, f"{entry['topic']} has no governing master"
        assert (REPO_ROOT / entry["schema"]).is_file()
